AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  GraphQLGet:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: "com.lovelessgeek.housemanager.api.handler.GetRequestHandler::handleRequest"
      CodeUri: "./build/libs/api-all.jar"
      Events:
        IndexApi:
          Type: "Api"
          Properties:
            Path: "/v1/graphql"
            Method: "get"
      Runtime: "java8"
      Timeout: 40
      MemorySize: 256
  GraphQLPost:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: "com.lovelessgeek.housemanager.api.handler.PostRequestHandler::handleRequest"
      CodeUri: "./build/libs/api-all.jar"
      Events:
        IndexApi:
          Type: "Api"
          Properties:
            Path: "/v1/graphql"
            Method: "post"
      Runtime: "java8"
      Timeout: 40
      MemorySize: 256
  TypeIntrospection:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: "com.lovelessgeek.housemanager.api.handler.TypeIntrospectionHandler::handleRequest"
      CodeUri: "./build/libs/api-all.jar"
      Events:
        IndexApi:
          Type: "Api"
          Properties:
            Path: "/v1/introspection/type"
            Method: "get"
      Runtime: "java8"
      Timeout: 40
      MemorySize: 256
Outputs:
  ProdEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"